// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import { defineConfig } from "prisma/config";
import { PrismaPg } from '@prisma/adapter-pg';


loadEnv();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error('DATABASE_URL environment variable is not set');
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});

/**
 * Helper for PrismaClient direct DB adapter usage
 *
 * Example:
 *   import { PrismaClient } from '@prisma/client';
 *   import { adapter } from '../prisma/prisma.config';
 *   const prisma = new PrismaClient({ adapter });
 */
export const adapter = new PrismaPg({ 
  connectionString: databaseUrl
});

